"""Partial type stubs for RPi.GPIO."""
from typing import List, Union

BCM: int
OUT: int
IN: int

def output(pin_number: int, value: Union[int, bool]) -> None: ...
def input(pin_number: int) -> int: ...
def setup(pin_number: int, mode: int) -> None: ...
def setmode(mode: int) -> None: ...
def cleanup(pins: List[int]) -> None: ...
def setwarnings(warnings: bool) -> None: ...
